import { db } from "@workspace/db";
import { exercisesTable } from "@workspace/db/schema";

const exercises = [
  // BACK
  { id: "0001", name: "Barbell Deadlift", bodyPart: "back", equipment: "barbell", gifUrl: "https://api.exercisedb.io/image/lHYiWqDhyGxXvK", target: "spine", secondaryMuscles: ["glutes", "hamstrings", "quads"], instructions: ["Stand with feet hip-width apart, bar over mid-foot.", "Grip the bar just outside your legs.", "Hinge at the hips and bend knees to lower to bar.", "Drive through your heels to stand up, keeping back straight.", "Lower the bar with control to the starting position."] },
  { id: "0002", name: "Pull-Up", bodyPart: "back", equipment: "body weight", gifUrl: "https://api.exercisedb.io/image/xg6kRHoHUkoPdm", target: "lats", secondaryMuscles: ["biceps", "rear deltoids", "rhomboids"], instructions: ["Hang from a pull-up bar with palms facing away, hands shoulder-width apart.", "Engage your core and pull your shoulder blades down.", "Pull yourself up until your chin clears the bar.", "Lower yourself back down with control."] },
  { id: "0003", name: "Bent Over Barbell Row", bodyPart: "back", equipment: "barbell", gifUrl: "https://api.exercisedb.io/image/3YfGBeHGwsDsj2", target: "upper back", secondaryMuscles: ["biceps", "lats", "rhomboids"], instructions: ["Stand with feet shoulder-width apart, hinge forward at the hips.", "Grip the barbell with an overhand grip, hands just outside your legs.", "Pull the bar to your lower chest, squeezing your shoulder blades.", "Lower the bar back down with control."] },
  { id: "0004", name: "Lat Pulldown", bodyPart: "back", equipment: "cable", gifUrl: "https://api.exercisedb.io/image/gBD4rCT5ygmXzH", target: "lats", secondaryMuscles: ["biceps", "rear deltoids"], instructions: ["Sit at the lat pulldown machine, securing your thighs under the pads.", "Grip the bar wider than shoulder-width.", "Pull the bar to your upper chest while keeping your back slightly arched.", "Slowly return to the starting position."] },
  { id: "0005", name: "Seated Cable Row", bodyPart: "back", equipment: "cable", gifUrl: "https://api.exercisedb.io/image/VFGbivWanOtBsO", target: "upper back", secondaryMuscles: ["biceps", "lats"], instructions: ["Sit at the cable row machine, feet on the platform, knees slightly bent.", "Grip the handle with both hands.", "Pull the handle to your abdomen, squeezing your shoulder blades.", "Extend your arms back out with control."] },
  { id: "0006", name: "T-Bar Row", bodyPart: "back", equipment: "barbell", gifUrl: "https://api.exercisedb.io/image/XbmFAbH3EwtBeK", target: "upper back", secondaryMuscles: ["biceps", "lats"], instructions: ["Stand over the T-bar and grab the handles.", "Hinge at the hips with a flat back.", "Pull the weight up to your chest.", "Lower it back down with control."] },
  { id: "0007", name: "Hyperextension", bodyPart: "back", equipment: "body weight", gifUrl: "https://api.exercisedb.io/image/vhXkbWWX7ciBre", target: "spine", secondaryMuscles: ["glutes", "hamstrings"], instructions: ["Position yourself on a hyperextension bench face-down.", "Cross your arms over your chest or clasp behind your head.", "Lower your torso until you feel a stretch in your hamstrings.", "Raise back up until your body is in a straight line."] },
  { id: "0008", name: "Dumbbell Row", bodyPart: "back", equipment: "dumbbell", gifUrl: "https://api.exercisedb.io/image/e3ILaTJBX5FEeq", target: "upper back", secondaryMuscles: ["biceps", "lats"], instructions: ["Place one hand and knee on a bench for support.", "Hold a dumbbell in the opposite hand.", "Pull the dumbbell up to your hip, keeping elbow close to body.", "Lower with control and repeat."] },
  // CHEST
  { id: "0009", name: "Barbell Bench Press", bodyPart: "chest", equipment: "barbell", gifUrl: "https://api.exercisedb.io/image/bGwQ5GFNIPFhIu", target: "pectorals", secondaryMuscles: ["triceps", "front deltoids"], instructions: ["Lie on a bench with feet flat on the floor.", "Grip the bar slightly wider than shoulder-width.", "Lower the bar to your chest with control.", "Press the bar back up to full arm extension."] },
  { id: "0010", name: "Dumbbell Bench Press", bodyPart: "chest", equipment: "dumbbell", gifUrl: "https://api.exercisedb.io/image/GiJUFjAi0zTHr1", target: "pectorals", secondaryMuscles: ["triceps", "front deltoids"], instructions: ["Lie on a bench holding a dumbbell in each hand at chest level.", "Press the dumbbells up until arms are fully extended.", "Lower them back down with control."] },
  { id: "0011", name: "Incline Barbell Bench Press", bodyPart: "chest", equipment: "barbell", gifUrl: "https://api.exercisedb.io/image/2iSRRImKXPy3yv", target: "pectorals", secondaryMuscles: ["triceps", "front deltoids"], instructions: ["Set bench to a 30-45 degree incline.", "Lie back and grip the bar slightly wider than shoulder-width.", "Lower the bar to your upper chest.", "Press back up to full arm extension."] },
  { id: "0012", name: "Push-Up", bodyPart: "chest", equipment: "body weight", gifUrl: "https://api.exercisedb.io/image/Mf3cBePAJGGBmq", target: "pectorals", secondaryMuscles: ["triceps", "front deltoids"], instructions: ["Start in a plank position with hands shoulder-width apart.", "Lower your chest toward the floor, keeping elbows at 45 degrees.", "Push back up to the starting position."] },
  { id: "0013", name: "Cable Chest Fly", bodyPart: "chest", equipment: "cable", gifUrl: "https://api.exercisedb.io/image/rMfUd7MHf6jtKx", target: "pectorals", secondaryMuscles: ["front deltoids"], instructions: ["Set pulleys to chest height and stand in the center.", "Hold handles and step forward with one foot.", "With a slight bend in the elbows, bring hands together in front of you.", "Slowly return to starting position."] },
  { id: "0014", name: "Pec Deck Machine", bodyPart: "chest", equipment: "leverage machine", gifUrl: "https://api.exercisedb.io/image/PbHkOstUy7nA8n", target: "pectorals", secondaryMuscles: [], instructions: ["Sit in the machine with back against the pad.", "Place forearms on the arm pads.", "Squeeze the pads together in front of you.", "Slowly release back to start."] },
  { id: "0015", name: "Decline Bench Press", bodyPart: "chest", equipment: "barbell", gifUrl: "https://api.exercisedb.io/image/cVBxJUm0F7WK19", target: "pectorals", secondaryMuscles: ["triceps"], instructions: ["Secure feet and lie on declined bench.", "Grip the bar wider than shoulder-width.", "Lower the bar to your lower chest.", "Press back up to full extension."] },
  { id: "0016", name: "Dips", bodyPart: "chest", equipment: "body weight", gifUrl: "https://api.exercisedb.io/image/D0YnPjT7FOVK6n", target: "pectorals", secondaryMuscles: ["triceps", "front deltoids"], instructions: ["Grip the parallel bars and support your body at arm's length.", "Lean forward slightly and lower yourself by bending your elbows.", "Push back up when your upper arms are parallel to the floor."] },
  // SHOULDERS
  { id: "0017", name: "Barbell Overhead Press", bodyPart: "shoulders", equipment: "barbell", gifUrl: "https://api.exercisedb.io/image/NJFBKtQPX6mQ1n", target: "delts", secondaryMuscles: ["triceps", "upper traps"], instructions: ["Stand with feet shoulder-width apart, gripping the bar just outside shoulder-width.", "Unrack the bar to shoulder height.", "Press the bar overhead until arms are fully extended.", "Lower the bar back to shoulder level with control."] },
  { id: "0018", name: "Dumbbell Lateral Raise", bodyPart: "shoulders", equipment: "dumbbell", gifUrl: "https://api.exercisedb.io/image/kMY26R5cBHN98n", target: "delts", secondaryMuscles: [], instructions: ["Stand holding dumbbells at your sides.", "Raise the dumbbells out to the side until your arms are parallel to the floor.", "Slowly lower them back down."] },
  { id: "0019", name: "Arnold Press", bodyPart: "shoulders", equipment: "dumbbell", gifUrl: "https://api.exercisedb.io/image/GW7vRHPk1pOALM", target: "delts", secondaryMuscles: ["triceps"], instructions: ["Sit holding dumbbells at shoulder height with palms facing you.", "As you press up, rotate your palms away from you.", "Continue pressing until arms are fully extended.", "Reverse the rotation as you lower."] },
  { id: "0020", name: "Face Pull", bodyPart: "shoulders", equipment: "cable", gifUrl: "https://api.exercisedb.io/image/6FVVdGnBLfqRk5", target: "delts", secondaryMuscles: ["rear deltoids", "rhomboids"], instructions: ["Set cable to face height with a rope attachment.", "Pull the rope toward your face, separating your hands at the end.", "Squeeze your rear deltoids at the peak.", "Slowly return to start."] },
  { id: "0021", name: "Upright Row", bodyPart: "shoulders", equipment: "barbell", gifUrl: "https://api.exercisedb.io/image/p2EMsmkXs9oAGd", target: "delts", secondaryMuscles: ["upper traps", "biceps"], instructions: ["Stand holding a barbell with an overhand grip, hands shoulder-width apart.", "Pull the bar up to chin height, keeping it close to your body.", "Lower the bar back down with control."] },
  { id: "0022", name: "Cable Lateral Raise", bodyPart: "shoulders", equipment: "cable", gifUrl: "https://api.exercisedb.io/image/XCHfmMjQStGAbD", target: "delts", secondaryMuscles: [], instructions: ["Stand next to a low cable machine, holding the handle in the far hand.", "Raise your arm out to the side until parallel to the floor.", "Slowly lower back down."] },
  // UPPER ARMS (Biceps & Triceps)
  { id: "0023", name: "Barbell Curl", bodyPart: "upper arms", equipment: "barbell", gifUrl: "https://api.exercisedb.io/image/hLjNXs8tNeaFEe", target: "biceps brachii", secondaryMuscles: ["brachialis", "brachioradialis"], instructions: ["Stand holding a barbell with an underhand grip, hands shoulder-width apart.", "Keep your elbows close to your sides.", "Curl the bar up to your shoulders.", "Slowly lower back down."] },
  { id: "0024", name: "Dumbbell Bicep Curl", bodyPart: "upper arms", equipment: "dumbbell", gifUrl: "https://api.exercisedb.io/image/8i5TodJqVfAd37", target: "biceps brachii", secondaryMuscles: ["brachialis"], instructions: ["Stand holding a dumbbell in each hand at arm's length.", "Curl the weights up to your shoulders, keeping elbows close to your body.", "Lower back down with control."] },
  { id: "0025", name: "Hammer Curl", bodyPart: "upper arms", equipment: "dumbbell", gifUrl: "https://api.exercisedb.io/image/LqnPDCwk9HNL4O", target: "brachialis", secondaryMuscles: ["biceps brachii", "brachioradialis"], instructions: ["Stand holding dumbbells with palms facing your body.", "Curl the weights up without rotating your wrist.", "Squeeze at the top, then lower with control."] },
  { id: "0026", name: "Tricep Pushdown", bodyPart: "upper arms", equipment: "cable", gifUrl: "https://api.exercisedb.io/image/U9cP1nLAFXuHMK", target: "triceps brachii", secondaryMuscles: [], instructions: ["Attach a straight or V-bar to the high cable.", "Stand facing the machine, grip the bar with an overhand grip.", "Push the bar down until your arms are fully extended.", "Slowly return to starting position."] },
  { id: "0027", name: "Skull Crusher", bodyPart: "upper arms", equipment: "barbell", gifUrl: "https://api.exercisedb.io/image/qkIZBhqAQKcbHu", target: "triceps brachii", secondaryMuscles: [], instructions: ["Lie on a bench holding an EZ-bar with a narrow grip.", "Lower the bar toward your forehead by bending at the elbows.", "Extend your arms back to the starting position."] },
  { id: "0028", name: "Concentration Curl", bodyPart: "upper arms", equipment: "dumbbell", gifUrl: "https://api.exercisedb.io/image/Y7fqBFhkNasN55", target: "biceps brachii", secondaryMuscles: [], instructions: ["Sit on a bench, rest your elbow on the inside of your thigh.", "Curl the dumbbell up to your shoulder.", "Squeeze at the top, then lower with control."] },
  { id: "0029", name: "Cable Tricep Extension", bodyPart: "upper arms", equipment: "cable", gifUrl: "https://api.exercisedb.io/image/mMf3qV2V4Xu4DZ", target: "triceps brachii", secondaryMuscles: [], instructions: ["Set the cable overhead. Grab the rope with both hands.", "Keep elbows pointing forward, extend arms downward.", "Return to starting position with control."] },
  // LOWER ARMS (Forearms)
  { id: "0030", name: "Wrist Curl", bodyPart: "lower arms", equipment: "barbell", gifUrl: "https://api.exercisedb.io/image/oJR9d8RUhwBXTk", target: "wrist flexors", secondaryMuscles: [], instructions: ["Sit on a bench, forearms resting on your thighs, palms up.", "Hold a barbell with an underhand grip.", "Lower the barbell as far as possible.", "Curl your wrists up as far as possible."] },
  { id: "0031", name: "Reverse Wrist Curl", bodyPart: "lower arms", equipment: "barbell", gifUrl: "https://api.exercisedb.io/image/YF8YiVBl3e5SaB", target: "wrist extensors", secondaryMuscles: [], instructions: ["Sit on a bench, forearms resting on thighs, palms facing down.", "Lower the barbell as far as possible.", "Curl your wrists up as far as possible."] },
  { id: "0032", name: "Farmer's Walk", bodyPart: "lower arms", equipment: "dumbbell", gifUrl: "https://api.exercisedb.io/image/BrS2WzEPaqn6bz", target: "wrist flexors", secondaryMuscles: ["traps", "core"], instructions: ["Pick up heavy dumbbells in each hand.", "Walk forward maintaining an upright posture.", "Keep shoulders back and core engaged."] },
  // UPPER LEGS (Quads & Hamstrings)
  { id: "0033", name: "Barbell Squat", bodyPart: "upper legs", equipment: "barbell", gifUrl: "https://api.exercisedb.io/image/p6iqNkPkITy0Pj", target: "quads", secondaryMuscles: ["glutes", "hamstrings", "calves"], instructions: ["Position the bar on your upper back and stand with feet shoulder-width apart.", "Bend at the knees and hips to lower into a squat.", "Keep your chest up and knees tracking over your toes.", "Push through your heels to stand back up."] },
  { id: "0034", name: "Leg Press", bodyPart: "upper legs", equipment: "leverage machine", gifUrl: "https://api.exercisedb.io/image/jXLRvRLRbMGfVP", target: "quads", secondaryMuscles: ["glutes", "hamstrings"], instructions: ["Sit in the leg press machine with feet shoulder-width apart on the platform.", "Lower the platform until your knees are at 90 degrees.", "Press through your heels to extend your legs.", "Return to starting position with control."] },
  { id: "0035", name: "Romanian Deadlift", bodyPart: "upper legs", equipment: "barbell", gifUrl: "https://api.exercisedb.io/image/rVPIlJH09hmaCn", target: "hamstrings", secondaryMuscles: ["glutes", "spine"], instructions: ["Stand holding a barbell at hip height.", "Hinge at the hips, lowering the bar along your legs.", "Feel a stretch in your hamstrings, then drive hips forward to stand."] },
  { id: "0036", name: "Leg Extension", bodyPart: "upper legs", equipment: "leverage machine", gifUrl: "https://api.exercisedb.io/image/PbHkOstUy7nA8n", target: "quads", secondaryMuscles: [], instructions: ["Sit in the leg extension machine, ankles under the pad.", "Extend your legs until straight.", "Slowly lower back to starting position."] },
  { id: "0037", name: "Leg Curl", bodyPart: "upper legs", equipment: "leverage machine", gifUrl: "https://api.exercisedb.io/image/CdGRJt5EuRnX4g", target: "hamstrings", secondaryMuscles: [], instructions: ["Lie face down on the leg curl machine.", "Place your ankles under the pads.", "Curl your legs up toward your glutes.", "Slowly lower back down."] },
  { id: "0038", name: "Lunge", bodyPart: "upper legs", equipment: "body weight", gifUrl: "https://api.exercisedb.io/image/0G5ZaMaJtv5VqS", target: "quads", secondaryMuscles: ["glutes", "hamstrings"], instructions: ["Stand tall with feet together.", "Step forward with one foot and lower your back knee toward the floor.", "Push back through your front heel to return to standing."] },
  { id: "0039", name: "Bulgarian Split Squat", bodyPart: "upper legs", equipment: "dumbbell", gifUrl: "https://api.exercisedb.io/image/Qi0SBvbKPhT5ne", target: "quads", secondaryMuscles: ["glutes", "hamstrings"], instructions: ["Stand in front of a bench. Place one foot behind you on the bench.", "Lower your back knee toward the floor.", "Drive through your front heel to return to starting position."] },
  { id: "0040", name: "Hack Squat", bodyPart: "upper legs", equipment: "leverage machine", gifUrl: "https://api.exercisedb.io/image/CGBKBK9wdHOV0G", target: "quads", secondaryMuscles: ["glutes"], instructions: ["Position yourself in the hack squat machine.", "Lower yourself until thighs are parallel to the platform.", "Push through your heels to return to starting position."] },
  // LOWER LEGS (Calves)
  { id: "0041", name: "Standing Calf Raise", bodyPart: "lower legs", equipment: "leverage machine", gifUrl: "https://api.exercisedb.io/image/ERUdGlr4I3rU97", target: "calves", secondaryMuscles: [], instructions: ["Stand on the calf raise machine with shoulders under the pads.", "Rise up onto your toes as high as possible.", "Hold at the top, then slowly lower your heels below the platform."] },
  { id: "0042", name: "Seated Calf Raise", bodyPart: "lower legs", equipment: "leverage machine", gifUrl: "https://api.exercisedb.io/image/RJ2BZK6TsZWC0H", target: "calves", secondaryMuscles: [], instructions: ["Sit in the seated calf raise machine, pads resting on your thighs.", "Rise onto your toes as high as possible.", "Slowly lower your heels back down."] },
  { id: "0043", name: "Donkey Calf Raise", bodyPart: "lower legs", equipment: "leverage machine", gifUrl: "https://api.exercisedb.io/image/T1HzDjFWMwHjep", target: "calves", secondaryMuscles: [], instructions: ["Hinge at the hips with upper body parallel to the floor.", "Rise up onto your toes, squeezing your calves.", "Lower back down with control."] },
  { id: "0044", name: "Jump Rope", bodyPart: "lower legs", equipment: "rope", gifUrl: "https://api.exercisedb.io/image/ymFKn1mUYKByc0", target: "calves", secondaryMuscles: ["cardio"], instructions: ["Hold the jump rope handles at hip height.", "Swing the rope over your head and jump over it with both feet.", "Keep a steady rhythm."] },
  // HIPS (Glutes)
  { id: "0045", name: "Hip Thrust", bodyPart: "hips", equipment: "barbell", gifUrl: "https://api.exercisedb.io/image/w7RDMnXA3zQPF0", target: "glutes", secondaryMuscles: ["hamstrings"], instructions: ["Sit with your upper back against a bench, barbell across your hips.", "Plant feet flat on the floor, hip-width apart.", "Drive your hips up until body is straight.", "Squeeze your glutes at the top, then lower back down."] },
  { id: "0046", name: "Glute Kickback", bodyPart: "hips", equipment: "cable", gifUrl: "https://api.exercisedb.io/image/L0e8TK6MaH1BbF", target: "glutes", secondaryMuscles: [], instructions: ["Attach an ankle strap to a low cable. Get on all fours.", "Kick one leg back until it's fully extended.", "Squeeze your glute at the top, then return."] },
  { id: "0047", name: "Sumo Squat", bodyPart: "hips", equipment: "dumbbell", gifUrl: "https://api.exercisedb.io/image/yR8BRFLGhSBX6o", target: "glutes", secondaryMuscles: ["quads", "hamstrings"], instructions: ["Stand with feet wider than shoulder-width, toes pointed out.", "Hold a dumbbell between your legs.", "Lower into a squat, keeping back straight.", "Drive through your heels to stand back up."] },
  { id: "0048", name: "Abductor Machine", bodyPart: "hips", equipment: "leverage machine", gifUrl: "https://api.exercisedb.io/image/QwbH6FLbHnKpG5", target: "abductors", secondaryMuscles: [], instructions: ["Sit in the abductor machine with your legs against the pads.", "Push your legs outward against resistance.", "Slowly bring them back together."] },
  // WAIST (Core/Abs)
  { id: "0049", name: "Crunch", bodyPart: "waist", equipment: "body weight", gifUrl: "https://api.exercisedb.io/image/lHYiWqDhyGxXvK", target: "abs", secondaryMuscles: [], instructions: ["Lie on your back with knees bent, feet flat on the floor.", "Place hands behind your head.", "Curl your shoulders off the floor using your abs.", "Slowly lower back down."] },
  { id: "0050", name: "Plank", bodyPart: "waist", equipment: "body weight", gifUrl: "https://api.exercisedb.io/image/ZoZCoLYq9IDpBp", target: "abs", secondaryMuscles: ["shoulders", "glutes"], instructions: ["Get into a push-up position, resting on your forearms.", "Keep your body in a straight line from head to heels.", "Hold for the desired time, keeping core tight."] },
  { id: "0051", name: "Russian Twist", bodyPart: "waist", equipment: "body weight", gifUrl: "https://api.exercisedb.io/image/LnsDMcMCvlq8ME", target: "abs", secondaryMuscles: ["obliques"], instructions: ["Sit on the floor with knees bent, lean back slightly.", "Lift feet off the ground.", "Rotate your torso side to side."] },
  { id: "0052", name: "Leg Raise", bodyPart: "waist", equipment: "body weight", gifUrl: "https://api.exercisedb.io/image/qCOOxVr2GPr0JV", target: "abs", secondaryMuscles: ["hip flexors"], instructions: ["Lie flat on your back with legs straight.", "Keeping legs together, raise them to 90 degrees.", "Slowly lower them back down without touching the floor."] },
  { id: "0053", name: "Cable Crunch", bodyPart: "waist", equipment: "cable", gifUrl: "https://api.exercisedb.io/image/GgvBZGcAOGEzMC", target: "abs", secondaryMuscles: [], instructions: ["Kneel in front of a cable machine with a rope attachment.", "Hold the rope at your head.", "Crunch your abs, pulling the weight down.", "Slowly return to start."] },
  { id: "0054", name: "Ab Wheel Rollout", bodyPart: "waist", equipment: "wheel roller", gifUrl: "https://api.exercisedb.io/image/5p0TakAmxT2Vbu", target: "abs", secondaryMuscles: ["shoulders", "lats"], instructions: ["Kneel on the floor holding the ab wheel.", "Roll out as far as you can while keeping your back straight.", "Roll back to the starting position using your core."] },
  // NECK
  { id: "0055", name: "Neck Flexion", bodyPart: "neck", equipment: "body weight", gifUrl: "https://api.exercisedb.io/image/qkIZBhqAQKcbHu", target: "neck", secondaryMuscles: [], instructions: ["Sit or stand upright.", "Gently tilt your head forward, bringing chin to chest.", "Hold briefly, then return to neutral."] },
  { id: "0056", name: "Neck Extension", bodyPart: "neck", equipment: "body weight", gifUrl: "https://api.exercisedb.io/image/qkIZBhqAQKcbHu", target: "neck", secondaryMuscles: [], instructions: ["Sit or stand upright.", "Gently tilt your head backward.", "Hold briefly, then return to neutral."] },
  // CARDIO
  { id: "0057", name: "Running on Treadmill", bodyPart: "cardio", equipment: "treadmill", gifUrl: "https://api.exercisedb.io/image/lHYiWqDhyGxXvK", target: "cardiovascular system", secondaryMuscles: ["quads", "hamstrings", "calves"], instructions: ["Set the treadmill to your desired speed and incline.", "Run with a natural gait, landing midfoot.", "Maintain an upright posture.", "Cool down with a walk at the end."] },
  { id: "0058", name: "Cycling on Stationary Bike", bodyPart: "cardio", equipment: "stationary bike", gifUrl: "https://api.exercisedb.io/image/lHYiWqDhyGxXvK", target: "cardiovascular system", secondaryMuscles: ["quads", "hamstrings"], instructions: ["Adjust the seat height so your legs are almost fully extended at the bottom of the pedal stroke.", "Set resistance to your desired level.", "Pedal at a steady cadence.", "Keep your back straight and core engaged."] },
  { id: "0059", name: "Jumping Jack", bodyPart: "cardio", equipment: "body weight", gifUrl: "https://api.exercisedb.io/image/ymFKn1mUYKByc0", target: "cardiovascular system", secondaryMuscles: ["calves", "shoulders"], instructions: ["Stand with feet together and arms at your sides.", "Jump your feet out to the sides while raising your arms overhead.", "Jump back to the starting position."] },
  { id: "0060", name: "Burpee", bodyPart: "cardio", equipment: "body weight", gifUrl: "https://api.exercisedb.io/image/lHYiWqDhyGxXvK", target: "cardiovascular system", secondaryMuscles: ["chest", "quads", "shoulders"], instructions: ["Stand with feet shoulder-width apart.", "Drop into a squat and place hands on the floor.", "Jump your feet back into a push-up position.", "Perform a push-up.", "Jump feet forward to squat position.", "Explosively jump up with arms overhead."] },
  // EZ BARBELL
  { id: "0061", name: "EZ Bar Curl", bodyPart: "upper arms", equipment: "ez barbell", gifUrl: "https://api.exercisedb.io/image/hLjNXs8tNeaFEe", target: "biceps brachii", secondaryMuscles: ["brachialis"], instructions: ["Stand holding an EZ bar with a narrow underhand grip.", "Curl the bar up to your shoulders.", "Slowly lower it back down."] },
  { id: "0062", name: "EZ Bar Tricep Extension", bodyPart: "upper arms", equipment: "ez barbell", gifUrl: "https://api.exercisedb.io/image/qkIZBhqAQKcbHu", target: "triceps brachii", secondaryMuscles: [], instructions: ["Lie on a bench holding an EZ bar above your chest.", "Bend elbows to lower the bar toward your forehead.", "Extend arms back to starting position."] },
  // KETTLEBELL
  { id: "0063", name: "Kettlebell Swing", bodyPart: "hips", equipment: "kettlebell", gifUrl: "https://api.exercisedb.io/image/w7RDMnXA3zQPF0", target: "glutes", secondaryMuscles: ["hamstrings", "spine", "core"], instructions: ["Stand with feet shoulder-width apart, kettlebell on the floor.", "Hinge at the hips and grab the kettlebell.", "Drive your hips forward to swing the kettlebell to chest height.", "Allow it to swing back between your legs and repeat."] },
  { id: "0064", name: "Kettlebell Goblet Squat", bodyPart: "upper legs", equipment: "kettlebell", gifUrl: "https://api.exercisedb.io/image/p6iqNkPkITy0Pj", target: "quads", secondaryMuscles: ["glutes", "core"], instructions: ["Hold a kettlebell at chest height with both hands.", "Stand with feet shoulder-width apart.", "Lower into a squat, keeping chest up.", "Push through heels to stand back up."] },
  { id: "0065", name: "Kettlebell Turkish Get-Up", bodyPart: "upper arms", equipment: "kettlebell", gifUrl: "https://api.exercisedb.io/image/NJFBKtQPX6mQ1n", target: "delts", secondaryMuscles: ["core", "glutes", "quads"], instructions: ["Lie on your back holding a kettlebell above one shoulder.", "Roll to your elbow, then your hand.", "Sweep your leg through and come to a lunge position.", "Stand up fully.", "Reverse the movement to return to the floor."] },
  // RESISTANCE BAND
  { id: "0066", name: "Resistance Band Bicep Curl", bodyPart: "upper arms", equipment: "resistance band", gifUrl: "https://api.exercisedb.io/image/8i5TodJqVfAd37", target: "biceps brachii", secondaryMuscles: [], instructions: ["Stand on the band with both feet, holding the handles.", "Curl your hands up to your shoulders.", "Slowly lower back down."] },
  { id: "0067", name: "Resistance Band Lateral Walk", bodyPart: "hips", equipment: "resistance band", gifUrl: "https://api.exercisedb.io/image/QwbH6FLbHnKpG5", target: "abductors", secondaryMuscles: ["glutes"], instructions: ["Place a band around your ankles.", "Bend slightly at the hips and knees.", "Step sideways, maintaining tension in the band."] },
  // OLYMPIC BARBELL
  { id: "0068", name: "Clean and Jerk", bodyPart: "upper legs", equipment: "olympic barbell", gifUrl: "https://api.exercisedb.io/image/p6iqNkPkITy0Pj", target: "quads", secondaryMuscles: ["glutes", "shoulders", "traps"], instructions: ["Start with the bar on the floor, squat down to grip it.", "Explosively pull the bar up and catch it at shoulder height in a squat.", "Stand up, then dip slightly and drive the bar overhead.", "Lock out your arms and stand."] },
  { id: "0069", name: "Power Clean", bodyPart: "upper legs", equipment: "olympic barbell", gifUrl: "https://api.exercisedb.io/image/rVPIlJH09hmaCn", target: "quads", secondaryMuscles: ["glutes", "hamstrings", "traps"], instructions: ["Stand with bar over your mid-foot.", "Pull the bar up explosively using legs, hips, and back.", "Drop under the bar catching it at shoulder height.", "Stand to complete the rep."] },
  // SMITH MACHINE
  { id: "0070", name: "Smith Machine Squat", bodyPart: "upper legs", equipment: "smith machine", gifUrl: "https://api.exercisedb.io/image/p6iqNkPkITy0Pj", target: "quads", secondaryMuscles: ["glutes", "hamstrings"], instructions: ["Position the bar on the Smith Machine at shoulder height.", "Place it on your upper back and unrack it.", "Lower into a squat, then press back up."] },
];

async function seed() {
  console.log(`Seeding ${exercises.length} exercises...`);
  
  for (const exercise of exercises) {
    await db
      .insert(exercisesTable)
      .values({
        id: exercise.id,
        name: exercise.name,
        bodyPart: exercise.bodyPart,
        equipment: exercise.equipment,
        gifUrl: exercise.gifUrl,
        target: exercise.target,
        secondaryMuscles: exercise.secondaryMuscles,
        instructions: exercise.instructions,
      })
      .onConflictDoNothing();
  }

  console.log("✅ Exercises seeded successfully!");
}

seed().catch(console.error).finally(() => process.exit(0));
